-- Milestone 2: Marketplace schema + RLS
-- Run this in Supabase SQL Editor for an empty project.

begin;

create extension if not exists pgcrypto;

-- Enum for listing lifecycle.
do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'listing_status'
      and n.nspname = 'public'
  ) then
    create type public.listing_status as enum ('draft', 'published', 'sold', 'archived');
  end if;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_length check (display_name is null or char_length(display_name) between 1 and 80)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  created_at timestamptz not null default now(),
  constraint categories_slug_format check (slug = lower(slug) and slug ~ '^[a-z0-9-]+$')
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint not null references public.categories(id),
  title text not null,
  description text not null,
  price_amount numeric(12,2) not null,
  currency_code text not null default 'INR',
  status public.listing_status not null default 'draft',
  location_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  sold_at timestamptz,
  constraint listings_title_length check (char_length(title) between 3 and 120),
  constraint listings_description_length check (char_length(description) between 10 and 4000),
  constraint listings_price_non_negative check (price_amount >= 0),
  constraint listings_currency_code_format check (currency_code ~ '^[A-Z]{3}$')
);

create table if not exists public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint listing_images_sort_non_negative check (sort_order >= 0),
  constraint listing_images_url_non_empty check (char_length(trim(image_url)) > 0)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint conversations_buyer_not_seller check (buyer_id <> seller_id),
  constraint conversations_unique_listing_pair unique (listing_id, buyer_id, seller_id)
);

create table if not exists public.conversation_participants (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint messages_body_length check (char_length(trim(body)) between 1 and 3000)
);

-- Generic updated_at helper.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Auto-create profile row on signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  derived_name text;
begin
  derived_name := split_part(new.email, '@', 1);

  insert into public.profiles (id, display_name)
  values (new.id, nullif(derived_name, ''))
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
  before update on public.listings
  for each row execute function public.set_updated_at();

-- Keep listing lifecycle timestamps consistent.
create or replace function public.sync_listing_timestamps()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'published' and old.status <> 'published' and new.published_at is null then
    new.published_at = now();
  end if;

  if new.status = 'sold' and old.status <> 'sold' and new.sold_at is null then
    new.sold_at = now();
  end if;

  if new.status <> 'published' and new.status <> 'sold' then
    if old.status = 'published' then
      new.published_at = old.published_at;
    end if;
    if old.status = 'sold' then
      new.sold_at = old.sold_at;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists listings_sync_timestamps on public.listings;
create trigger listings_sync_timestamps
  before update on public.listings
  for each row execute function public.sync_listing_timestamps();

-- One function to create/get a listing-scoped 1:1 conversation and ensure participants exist.
create or replace function public.start_listing_conversation(p_listing_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_buyer_id uuid;
  v_seller_id uuid;
  v_status public.listing_status;
  v_conversation_id uuid;
begin
  v_buyer_id := auth.uid();
  if v_buyer_id is null then
    raise exception 'Authentication required';
  end if;

  select l.seller_id, l.status
    into v_seller_id, v_status
  from public.listings l
  where l.id = p_listing_id;

  if v_seller_id is null then
    raise exception 'Listing not found';
  end if;

  if v_seller_id = v_buyer_id then
    raise exception 'Seller cannot start chat with own listing';
  end if;

  if v_status <> 'published' then
    raise exception 'Listing must be published to start chat';
  end if;

  insert into public.conversations (listing_id, buyer_id, seller_id)
  values (p_listing_id, v_buyer_id, v_seller_id)
  on conflict (listing_id, buyer_id, seller_id) do update
    set listing_id = excluded.listing_id
  returning id into v_conversation_id;

  insert into public.conversation_participants (conversation_id, user_id)
  values (v_conversation_id, v_buyer_id), (v_conversation_id, v_seller_id)
  on conflict do nothing;

  return v_conversation_id;
end;
$$;

grant execute on function public.start_listing_conversation(uuid) to authenticated;

-- Indexes for listing feed and chat performance.
create index if not exists idx_listings_public_feed
  on public.listings (status, category_id, created_at desc);

create index if not exists idx_listings_seller_status
  on public.listings (seller_id, status, created_at desc);

create index if not exists idx_listing_images_listing_sort
  on public.listing_images (listing_id, sort_order);

create index if not exists idx_conversations_buyer_created
  on public.conversations (buyer_id, created_at desc);

create index if not exists idx_conversations_seller_created
  on public.conversations (seller_id, created_at desc);

create index if not exists idx_messages_conversation_created
  on public.messages (conversation_id, created_at asc);

create index if not exists idx_messages_sender_created
  on public.messages (sender_id, created_at desc);

-- Seed categories for Buy filters.
insert into public.categories (slug, name)
values
  ('electronics', 'Electronics'),
  ('fashion', 'Fashion'),
  ('home', 'Home'),
  ('books', 'Books'),
  ('sports', 'Sports'),
  ('services', 'Services'),
  ('others', 'Others')
on conflict (slug) do update
set name = excluded.name;

-- Enable RLS.
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;

-- Profiles: public read, owner write.
drop policy if exists profiles_read_all on public.profiles;
create policy profiles_read_all
  on public.profiles
  for select
  using (true);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
  on public.profiles
  for insert
  with check (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Categories: public read only.
drop policy if exists categories_read_all on public.categories;
create policy categories_read_all
  on public.categories
  for select
  using (true);

-- Listings: public read published, seller read/write own.
drop policy if exists listings_read_published_or_own on public.listings;
create policy listings_read_published_or_own
  on public.listings
  for select
  using (status = 'published' or seller_id = auth.uid());

drop policy if exists listings_insert_own on public.listings;
create policy listings_insert_own
  on public.listings
  for insert
  with check (seller_id = auth.uid());

drop policy if exists listings_update_own on public.listings;
create policy listings_update_own
  on public.listings
  for update
  using (seller_id = auth.uid())
  with check (seller_id = auth.uid());

drop policy if exists listings_delete_own on public.listings;
create policy listings_delete_own
  on public.listings
  for delete
  using (seller_id = auth.uid());

-- Listing images: visible with listing visibility, only owner can mutate.
drop policy if exists listing_images_read_visible on public.listing_images;
create policy listing_images_read_visible
  on public.listing_images
  for select
  using (
    exists (
      select 1
      from public.listings l
      where l.id = listing_images.listing_id
        and (l.status = 'published' or l.seller_id = auth.uid())
    )
  );

drop policy if exists listing_images_insert_owner on public.listing_images;
create policy listing_images_insert_owner
  on public.listing_images
  for insert
  with check (
    exists (
      select 1
      from public.listings l
      where l.id = listing_images.listing_id
        and l.seller_id = auth.uid()
    )
  );

drop policy if exists listing_images_update_owner on public.listing_images;
create policy listing_images_update_owner
  on public.listing_images
  for update
  using (
    exists (
      select 1
      from public.listings l
      where l.id = listing_images.listing_id
        and l.seller_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.listings l
      where l.id = listing_images.listing_id
        and l.seller_id = auth.uid()
    )
  );

drop policy if exists listing_images_delete_owner on public.listing_images;
create policy listing_images_delete_owner
  on public.listing_images
  for delete
  using (
    exists (
      select 1
      from public.listings l
      where l.id = listing_images.listing_id
        and l.seller_id = auth.uid()
    )
  );

-- Conversations: participants only.
drop policy if exists conversations_select_participants on public.conversations;
create policy conversations_select_participants
  on public.conversations
  for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

drop policy if exists conversations_insert_buyer on public.conversations;
create policy conversations_insert_buyer
  on public.conversations
  for insert
  with check (
    auth.uid() = buyer_id
    and buyer_id <> seller_id
    and exists (
      select 1
      from public.listings l
      where l.id = conversations.listing_id
        and l.seller_id = conversations.seller_id
        and l.status = 'published'
    )
  );

-- Conversation participants: participants can read; only buyer or seller can insert valid participant rows.
drop policy if exists conversation_participants_select_participants on public.conversation_participants;
create policy conversation_participants_select_participants
  on public.conversation_participants
  for select
  using (
    exists (
      select 1
      from public.conversation_participants cp2
      where cp2.conversation_id = conversation_participants.conversation_id
        and cp2.user_id = auth.uid()
    )
  );

drop policy if exists conversation_participants_insert_valid on public.conversation_participants;
create policy conversation_participants_insert_valid
  on public.conversation_participants
  for insert
  with check (
    exists (
      select 1
      from public.conversations c
      where c.id = conversation_participants.conversation_id
        and auth.uid() in (c.buyer_id, c.seller_id)
        and conversation_participants.user_id in (c.buyer_id, c.seller_id)
    )
  );

-- Messages: participants only; sender must be current user.
drop policy if exists messages_select_participants on public.messages;
create policy messages_select_participants
  on public.messages
  for select
  using (
    exists (
      select 1
      from public.conversation_participants cp
      where cp.conversation_id = messages.conversation_id
        and cp.user_id = auth.uid()
    )
  );

drop policy if exists messages_insert_participant_sender on public.messages;
create policy messages_insert_participant_sender
  on public.messages
  for insert
  with check (
    sender_id = auth.uid()
    and exists (
      select 1
      from public.conversation_participants cp
      where cp.conversation_id = messages.conversation_id
        and cp.user_id = auth.uid()
    )
  );

commit;
